<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dynamic Clean Blog</title>

    <!-- Prism Syntax Highlighting -->
<!--    <link rel="stylesheet" type="text/css" href="css/prism.css">-->
<!--    <script type="text/javascript" src="js/prism.js"></script> -->
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="<?=$this->dependencyPaths["bootstrapCss"]?>">

    <!-- Clean Blog Theme CSS -->
    <link rel="stylesheet" href="<?=$this->dependencyPaths["cleanblogCss"]?>">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery -->
    <script defer src="<?=$this->dependencyPaths["jQuery"]?>"></script>

    <!-- Bootstrap Core JavaScript -->
    <script defer src="<?=$this->dependencyPaths["bootstrapJavascript"]?>"></script>

    <!-- Clean Blog Theme JavaScript -->
    <script defer src="<?=$this->dependencyPaths["cleanblogJavascript"]?>"></script>
</head>

<body>

    <!-- Navigation -->
    <? include("views/partial-html/_navigation.phtml"); ?>

    <!-- Page Header -->
    <!-- Set your background image for this header on the include below. -->
    <? include("views/partial-html/_simple-header.phtml"); ?>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <? for($i = 0, $len = count($this->pagePostObjs); $i < $len; $i++) { ?>
                <div <?=$i==0?'id="postPreview1"':''?> class="post-preview">
                    <a href="/post/<?=$this->pagePostObjs[$i]->created?>/<?=$this->pagePostObjs[$i]->clean_url_title?>">
                        <h2 class="post-title">
                            <?=$this->pagePostObjs[$i]->title?>
                        </h2>
                        <h3 class="post-subtitle">
                            <?=$this->pagePostObjs[$i]->subtitle?>
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#"><?=$this->pagePostObjs[$i]->author_name?></a> on <?=date("F jS, Y",strtotime($this->pagePostObjs[$i]->created))?></p>
                </div>
                <hr/>
                <? } ?>

                <!-- Pager -->
                <ul class="pager">
                    <!-- prev page available if on any page other than page 1 -->
                    <? if ($this->pageNum > 1) { ?>
                    <li class="previous">
                        <a href="<?="/home/page/".($this->pageNum-1)."#postPreview1"?>"><span class="glyphicon glyphicon-chevron-left"></span> Newer Posts</a>
                    </li>
                    <? } ?>
                    <? if ($this->pageNum < $this->maxPageNum) { ?>
                    <li class="next">
                        <a href="<?="/home/page/".($this->pageNum+1)."#postPreview1"?>">Older Posts <span class="glyphicon glyphicon-chevron-right"></span></a>
                    </li>
                    <? } ?>
                </ul>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <? include("views/partial-html/_footer.phtml"); ?>

</body>

</html>
