<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - About</title>

    <? include("views/partial-html/_head-common.phtml"); ?>
</head>

<body>

    <!-- Navigation -->
    <? include("views/partial-html/_navigation.phtml"); ?>

    <!-- Page Header -->
    <!-- Set your background image for this header on the include below. -->
    <? include("views/partial-html/_simple-header.phtml"); ?>

    <hr>

    <!-- Footer -->
    <? include("views/partial-html/_footer.phtml"); ?>

</body>

</html>
