<header class="intro-header" style="background-image: url(<?=$this->headerInfo["bgndImgAddr"]?>)">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1><?=$this->headerInfo["mainHeading"]?></h1>
                    <hr class="small">
                    <span class="subheading"><?=$this->headerInfo["subHeading"]?></span>
                </div>
            </div>
        </div>
    </div>
</header>